### ISSUE TITLE
[ToIP Charter Section 6 Violation] ToIP should not be in possession of a copy of the Sovrin Glossary and its terms and definitions need be removed from the GitHub repository immediately

### ISSUE THREAD

**Issue by mwherman2000** [trustoverip/concepts-and-terminology#42]
## Issue/Feature Description

[ToIP Charter Section 6 Violation] ToIP should not be in possession of a copy of the Sovrin Glossary

## Proposed Solution

The Sovrin Glossary terms and definitions need be removed from the GitHub repository immediately

## Background

From: Michael Herman (Trusted Digital Web) 
Sent: February 26, 2021 5:52 PM
To: David Luchuk <dluchuk@contractor.linuxfoundation.org>
Subject: Per Section 6, ToIP should not be in possession of a copy of the Sovrin Glossary and its terms and definitions need be removed from the GitHub repository immediately

Based on the following 3 facts, ToIP should not be in possession of a copy of the Sovrin Glossary and its terms and definitions need to be removed from the GitHub repository immediately:

1.	Section 6: “Conditions for Contributions. A Steering Member, Associate, or Contributor may not make any Contribution unless that Steering Member, Associate or Contributor is the exclusive copyright owner of the Contribution or has sufficient copyright rights from the copyright owners to make the Contribution under the terms of this Project Charter and applicable Working Group Charter. The Steering Member, Associate, or Contributor must disclose the identities of all known copyright owners in the Contribution.”
2.	Sovrin Glossary Copyright: “© 2019 by Sovrin Foundation.” (https://docs.google.com/document/d/1gfIz5TT0cNp2kxGMLFXr19x1uoZsruUe_0glHst2fZ8/edit#)
3.	The Sovrin Foundation has no standing as a member of ToIP (per your response on today’s ToIP Orientation call: https://zoom.us/rec/share/hXsm8yPUeYDfHNdxXdKjzqqhng-LjayeXG_l5JyzgZCB2IRVPCKWTM0nBNKYrawg.MmqyEbBnJAk3OOqw).

ToIP should not be in possession of a copy of the Sovrin Glossary and its terms and definitions need to be removed from the GitHub repository immediately.

I suspect this applies to several additional Sovrin Foundation assets in addition to the Sovrin Glossary.

Best regards,
Michael Herman
Sovrin Foundation Self-Sovereignist

Self-Sovereign Blockchain Architect
Trusted Digital Web
Hyperonomy Digital Identity Lab
Parallelspace Corporation

**Comment by mwherman2000** [comment]
NOTE: This is not a Sovrin Foundation issue and SF shouldn't be confused with the Section 6 issue. 
Sovrin Foundation's CC license applies to "downstream recipients" ...of which ToIP is only one. There are no issues here.

The Section 6 issue is a ToIP internal issue only ... it's inability, as a recipient, to ingest/accept contributions in violation of Section 6. Nothing to do with SF.

CC licensing also has nothing to do with the issue. To raise it is a red herring.

**Comment by jstclair2019** [comment]
As noted in TOIP Slack #General channel:
2. Question: does the use of content drawn from the Sovrin Foundation Glossary, which is referenced in deliverables being developed through ToIP's Concepts & Terminology WG, represent a violation of S.6 in the Project Charter? Answer: the Sovrin Foundation Glossary is covered by the same Creative Commons 4.0 terms that apply to all deliverables being developed by the Concepts & Terminology WG. So long as a reasonable citation is made and a link to those Sovrin licensing terms are provided, ToIP can use this content. The contribution of content drawn from the Sovrin Glossary to the work of the Concepts & Terminology WG does not, in my view, represent a violation of S.6 of the Project Charter.
Recommend closing #42

**Comment by mwherman2000** [comment]
Below is my reply to David's posting that @jstclair2019 referenced above.  NOTE: This is *not* a Sovrin Foundation issue. It's a ToIP internal issue related to ToIP's internal restrictions for accepting and ingesting external content from copyright owners who are not members of ToIP. 

If this Section 6 Violation is allowed to stand, then ToIP should strike Section 6 from its Project Charter if it is not going to be enforced.  Fix our own house first.  

@DavidLuchuk Your response has confounded two unrelated and separate issues:
1. Sovrin's CC BY-SA licensing of the Sovrin Glossary to downstream recipients, and
2. ToIP's Project Charter Section 6 restrictions on what ToIP can accept and ingest from upstream sources.
...two different "ends of the pipe".

Section 6 of the ToIP Project Charter states:

>6. Conditions for Contributions. A Steering Member, Associate, or Contributor may not make any Contribution
unless that Steering Member, Associate or Contributor is the exclusive copyright owner of the Contribution or has
sufficient copyright rights from the copyright owners to make the Contribution under the terms of this Project
Charter and applicable Working Group Charter. The Steering Member, Associate, or Contributor must disclose the
identities of all known copyright owners in the Contribution.

Here are 2 additional facts:
a. The Sovrin Glossary V3 copyright statement states: © 2019 by Sovrin Foundation. (https://docs.google.com/document/d/1gfIz5TT0cNp2kxGMLFXr19x1uoZsruUe_0glHst2fZ8/edit#)
b. As you have communicated in the last (first?) ToIP Orientation call: The Sovrin Foundation has no standing as a member (at any level) at ToIP.
(recording: https://zoom.us/rec/share/hXsm8yPUeYDfHNdxXdKjzqqhng-LjayeXG_l5JyzgZCB2IRVPCKWTM0nBNKYrawg.MmqyEbBnJAk3OOqw)

Hence, based on the wording of Section 6 and the above 2 facts, ToIP should not be in possession of a copy of the Sovrin Glossary; neither its terms nor its definitions. Under Section 6, the Concepts and Terminology WG should have never allowed the Sovrin Glossary to be accepted and ingested into the ToIP GitHub repositories.

With respect to the Sovrin Glossary content accepted and ingested into the ToIP repositories, what are the consequences for:
- The contributed content? What is the prescribed resolution?
- The contributors who violated Section 6? What are their consequences?

To remove the existing Section 6 violation, I believe/recommend/suggest that all of the Sovrin Glossary terms and definitions need to be removed from the T&C GitHub repository based on the above. In addition, any and all other additional content from other organizations similar to the Sovrin Foundation who are not members of ToIP also need to be removed from the ToIP repositories.

Best regards,
Michael

**Comment by mwherman2000** [comment]
David Luchuk  10:59 AM
I appreciate this follow up Michael Herman. I think the points you've raised help clarify the way I approach this question. Sovrin is not a member of ToIP. That is true. However, the license that Sovrin applies to its Glossary grants the public permission to adapt, reproduce and share its contents. S.6 of the Project Charter establishes that a ToIP member must have sufficient rights to material in order to submit it as a Contribution. So, though Sovrin is not a member of ToIP, the license Sovrin applies to its Glossary makes it possible for a ToIP member to submit its contents as a Contribution. I hope that helps clarify how I view this question. Thanks.

Michael Herman  11:18 AM
@DavidLuchuk It's good we're getting deeper into the factual substance of S.6.
S.6 refers specifically to:
> ...Contributor is the exclusive copyright owner of the Contribution or
has sufficient copyright rights from the copyright owners to make the Contribution...

However, CC BY-SA only grants a downstream party a _license to use_ the content (with the BY and SA restrictions) - it is not an _assignment of copyright rights_.
... using these definitions from https://www.ic.gc.ca/eic/site/cipointernet-internetopic.nsf/eng/wr00054.html:
>Assignment. An assignment is the transfer of some or all of your rights to another party. An assignment can last for the entire term of the copyright or for part of it.
>Licence. A licence gives another party permission to use your work under certain conditions, but you keep ownership and maintain your rights.

Based on the above I believe the S.6 Violation for the Sovrin Glossary still exists. ...but this is as far as I can go with this

**Comment by mwherman2000** [comment]
By leaving the S.6 issue unresolved, the ToIP #steering-committee is, in turn, leaving all ToIP members with a legal risk should they check-in anything into a TOIP repository that they don't hold the exclusive copyrights for: i.e. when they are are not the original authors and copyright owners. Over and out.

**Comment by talltree** [comment]
Michael, herewith the text from Section 6 of the [ToIP Project Charter](https://docs.google.com/document/d/1hJ4YWH_efrYTRvzRI1N9YHwhUOyI_ScrPmI1D9T4_oc/edit?usp=sharing) that you have been referring to (emphasis added):

> **Conditions for Contributions.**  A Steering Member, Associate, or Contributor may not make any Contribution unless that Steering Member, Associate or Contributor is the exclusive copyright owner of the Contribution **or has sufficient copyright rights from the copyright owners** to make the Contribution under the terms of this Project Charter and applicable Working Group Charter.  The Steering Member, Associate, or Contributor must disclose the identities of all known copyright owners in the Contribution.

Next, copyright on the [Sovrin Glossary V3](https://docs.google.com/document/d/1gfIz5TT0cNp2kxGMLFXr19x1uoZsruUe_0glHst2fZ8/edit):

> © 2019 by Sovrin Foundation. This work is licensed under Creative Commons Attribution- ShareAlike 4.0 International License (http://creativecommons.org/licenses/by-sa/4.0/).

Next, the CC-By-SA 4.0 license terms:

> You are free to:
> 
> - Share — copy and redistribute the material in any medium or format
> - Adapt — remix, transform, and build upon the material
> - for any purpose, even commercially.
> 
> The licensor cannot revoke these freedoms as long as you follow the license terms.
> 
> - Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
> - ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

Finally, the licensing terms that apply to any deliverable from the ToIP Concepts and Terminology WG, from [the charter](https://wiki.trustoverip.org/pages/viewpage.action?pageId=65700): 

> Copyright mode: [Creative Commons Attribution 4.0](http://creativecommons.org/licenses/by/4.0/legalcode). 

Conclusion: the Sovrin Glossary was licensed by the Sovrin Foundation such that the CTWG had **sufficient copyright rights from the copyright owners** to make the contribution.

This has been confirmed with Linux Foundation counsel.

Case closed.

Lastly, both Daniel Hardman and I as co-chairs of the CTWG, as well as the Sovrin Governance Framework Working Group at the Sovrin Foundation, were fully aware of and in favor of this contribution when it took place. No one has had any reason to question this contribution, nor have we seen any reason to question this contribution in the light of what I just explained. **This is precisely the kind of content re-use that the CC-By-SA license was designed to encourage.** In fact we encourage all other communities who wish to participate in the shared terminology corpus being facilitated by the CTWG to contribute their glossaries under the exact same terms.

In courtesy to the community, it would be deeply appreciated if you would stop raising this concern.

**Comment by darrellodonnell** [comment]
I suggest this issue be closed.

**Comment by vinomaster** [comment]
As a contributor to the SF Glossary and well aware of that community's intent to **collaborate on broader industry usable glossaries** such as the CTWG effort which is now taking place in ToIP -- I have no issues with this re-use, especially as it has been confirmed by LF Counsel. 

I also suggest that the issue be closed by CTWG  one of the co-chairs.

**Comment by mwherman2000** [comment]
@talltree This issue is not about the Sovrin Foundation nor how the Sovrin Foundation licenses the Sovrin Glossary. SF has done everything correctly. Section 6 is strictly a internal ToIP issue.  Let me quote a couple of the key passages from above. 

## Key Point #1 - The Section 6 issue is at the ToIP end of the pipe: the point of acceptance and ingestion.

> 1. Sovrin's CC BY-SA licensing of the Sovrin Glossary to downstream recipients, and
> 2. ToIP's Project Charter Section 6 restrictions on what ToIP can accept and ingest from upstream sources.

...two different "ends of the pipe".  The Section 6 issue is at the ToIP end of the pipe: the point of acceptance and ingestion.

## Key Point #2 - S.6: ...Contributor is the exclusive copyright owner of the Contribution or has sufficient copyright rights from the copyright owners to make the Contribution...

The CC BY-SA license only _grants usage rights_ (_but you keep ownership and maintain your rights_.) - it does not _assign or reassign copyright rights_ ...the latter being the Section 6 requirement to accept and ingest content from an upstream copyright owner.  Here's the relevant quotations of the Canadian government website (my italicized introductory sentence):

_However, CC BY-SA grants a downstream party a license to use the content (with the BY and SA restrictions) - it is not an assignment of copyright rights ... using these definitions from [Canadian Intellectual Property Office: Transfer ownership](https://www.ic.gc.ca/eic/site/cipointernet-internetopic.nsf/eng/wr00054.html):_

> Assignment. An assignment is the transfer of some or all of your rights to another party. An assignment can last for the entire term of the copyright or for part of it.
> Licence. A licence gives another party permission to use your work under certain conditions, _but you keep ownership and maintain your rights_.

CC BY-SA does not assign downstream copyright rights.

Based on the above I believe the S.6 Violation for the Sovrin Glossary still exists. ...but this is as far as I can go with this.

By leaving the S.6 issue unresolved, the ToIP #steering-committee is, in turn, leaving all ToIP members with a legal risk should they check-in anything into a TOIP repository that they don't hold the exclusive copyrights for: i.e. when they are are not the original authors and copyright owners. Over and out.

**Comment by mwherman2000** [comment]
@vinomaster 

> I have no issues with this re-use, especially as it has been confirmed by LF Counsel.

@talltree

> This has been confirmed with Linux Foundation counsel.

These are not accurate statements. 

DavidL has said the LF/JDF cannot provide legal advice on this issue.  They redirected DavidL and ToIP to resolve this using the WG's processes and failing that, the issue is to be escalated to the ToIP Steering Committee.

**Comment by vinomaster** [comment]
Closing as `WONTFIX` as per request of the CTWG co-chairs.
